### ISSUE TITLE
Reorganize doesn't work for enums

### ISSUE THREAD

**Issue by BrianThorChristensen** [CloudReadySoftware/crs-al-language-extension#78]
Hi,
I love the reorganize function, but it doesn't work for enums or enumextensions.
Neither does the rename function.
And if you have "CRS.OnSaveAlFileAction": "Reorganize", you can no longer build the project.

**Comment by waldo1001** [comment]
thanks for this - need to update it, indeed!

**Comment by BrianThorChristensen** [comment]
I think it happens when I have placed the enum file inside a subfolder and the reorganize function moves it to the root folder.
I get the outout below in VSCode. And VSCode stops building until I restart VSCode. It seems the entire AL compiler gets unloaded.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.DiagnosticsProvider.<GetDocumentDiagnostics>d__2.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticsProvider.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.DiagnosticService.<GetAndEmitPartialDiagnostics>d__43.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticService.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.DiagnosticService.<ListenForBufferChanges>d__37.MoveNext() in C:\a\361\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\DiagnosticService.cs:line 250
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 12:30:34 PM] Connection to server got closed. Server will restart.
[Error - 12:30:34 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12)
[Error - 12:30:34 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12)
[Error - 12:30:34 PM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:1864:38)
	at LanguageClient.handleConnectionClosed (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\main.js:106:15)
	at closeHandler (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-languageclient\lib\client.js:1852:18)
	at CallbackList.invoke (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\messageWriter.js:57:27)
	at Socket.<anonymous> (C:\Users\btcadm\.vscode\extensions\microsoft.al-2.0.42188\node_modules\vscode-jsonrpc\lib\messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by waldo1001** [comment]
ok, let me fix the enum, and let's see 
thanks again!

**Comment by waldo1001** [comment]
new version online - would love your input!

**Comment by BrianThorChristensen** [comment]
Thanks alot, the reorganize function works like charm, but I still get the weird error.
I must investigate further...

**Comment by waldo1001** [comment]
In the stacktrace, I see "microsoft.al-2.0.42188"-references.. .  So I'm not sure it's my extension that causes this.  let's close it for now.  I will investigate more if I get the same errors!

**Comment by BrianThorChristensen** [comment]
I think maybe it happens if an object is renamed multible times.
With OnFileSaveAction: Reorganize or Rename.
I can't make it fail when OnFileSaveAction is DoNothing by manually renaming the files.
